name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:13
    #     env:
    #       POSTGRES_USER: testuser
    #       POSTGRES_PASSWORD: testpassword
    #       POSTGRES_DB: testdb
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd="pg_isready -U testuser"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=5

    #   redis:
    #     image: redis:6
    #     ports:
    #       - 6379:6379
    #     options: >-
    #       --health-cmd="redis-cli ping"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=5

    # env:
    #   DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb
    #   REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests